# Generated by Django 2.2.10 on 2021-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Ответ с текстом'), ('choice', 'Ответ с выбором одного ванианта'), ('m_choice', 'Ответ с выбором нескольких вариантов')], max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_start', models.DateField(auto_now_add=True, null=True)),
                ('date_finish', models.DateField(null=True)),
                ('description', models.TextField(default='Описание опроса.')),
            ],
        ),
    ]
